CREATE TABLE PRODUCTOS (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    CATEGORIA VARCHAR2(100),
    CANTIDAD NUMBER,
    PRECIO NUMBER,
    PROVEEDOR VARCHAR2(100)
);

INSERT INTO PRODUCTOS VALUES (1, 'Arroz', 'Alimentos', 20, 1500, 'Norte');
INSERT INTO PRODUCTOS VALUES (2, 'Leche', 'Lacteos', 8, 1200, 'Sur');
INSERT INTO PRODUCTOS VALUES (3, 'Leche', 'Lacteos', 8, 1200, 'Sur');

SELECT * FROM PRODUCTOS;